# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName("MainDialog")
        MainDialog.resize(1482, 576)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(MainDialog)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.helloLabel = QtWidgets.QLabel(MainDialog)
        self.helloLabel.setText("")
        self.helloLabel.setObjectName("helloLabel")
        self.verticalLayout.addWidget(self.helloLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(MainDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.yesButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.yesButton.setFont(font)
        self.yesButton.setObjectName("yesButton")
        self.horizontalLayout.addWidget(self.yesButton)
        self.noButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        self.noButton.setFont(font)
        self.noButton.setDefault(True)
        self.noButton.setObjectName("noButton")
        self.horizontalLayout.addWidget(self.noButton)
        spacerItem3 = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame)

        self.yes1(MainDialog)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)

    def yes1(self, MainDialog):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Сотни лет назад человечество было едва не уничтожено внезапно появившейся расой огромных существ - титанов.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Они питались исключительно людьми, а к другим живым существам не проявляли интереса.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Человечеству удалось выжить, укрывшись за тремя стенами - Роза, Мария и Сина. </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">И вот уже сто лет оно жило мирно без нападений титанов.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Однако в 845 году титаны Колоссальный и Бронированный, отличавшиеся от других высоким уровнем интеллекта и</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\"> способностью мгновенно появляться и исчезать, ворвались в южный форт стены Мария Сигансина и проломили саму стену Мария.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Человечество потеряло треть земель и пятую часть населения, но не утратило надежду, ведь его отважная армия продолжала отчаянно бороться с титанами.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Хотите вступить в ряды новобранцев и мочить титанов?</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Да"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Нет"))

    def yes2(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Добро пожаловать в кадетский корпус!</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">За три года здесь ты научишься профессионально сражаться с титанами, используя устройство пространственого маневрирования (УПМ) и особые клинки.</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Титаны крайне живучие и регенерирующеся ребята (как курицы и Росомаха вместе взятые - если им голову отрубить, еще живы останутся, а потом придут мстить).</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Но у них есть одно уязвимое место - сзади шеи в районе хребта.</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Как раз в это место и надо бить клинками, и если получится его отсечь, то титан уже окончательно окочурится.</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">А теперь научимся упрявлять УПМ. Для этого надо научиться держать равновесие, вися на тросах УПМ. Попробуем?</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Да"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Нет"))

    def yes3(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Поздравляю, новобранец, ты освоил азы управления УПМ, однако впереди еще много работы!</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Теперь научимся убивать титанов. Старайся резать специально сделанные чучела ровно позади шеи, другие ранения для титанов неопасны!</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Ты готов?</span></p></body></html>"))

    def yes4(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">three years later...</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Поздравляю, кадеты, вы окончили вашу подготовку и теперь можете выбрать, к какому подразделению вы хотите примкнуть.</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Разведкорпус"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Гарнизон"))

    def patrol(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Добро пожаловать в разведкорпус!</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Сюда вступают самые храбрые и отчаянные кадеты, готовые пожертвовать свои сердца на благо человечества.</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Вот ваше первое задание: вылазка за стену Роза для захвата титана-девианта живьем для дальнейших исследований.</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Справка: титаны-девианты отличаются от обычных нетипичным поведением: они не интересуются людьми, а идут напролом, куда им в голову взбредет.</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">За стеной не выжить без лошади. Помните, что в случае опасности вы всегда сможете позвать лошадь свистом.</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Вперед, по коням! Вылазка за стену №37 началась!</span></p>"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans Ms\'; font-size:10pt; color:#d30700;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Comic Sans Ms\'; font-size:10pt; color:#d30700;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">a few moments later...</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Всем внимание, впереди титан! Это обычный или девиант?</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Обычный"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Девиант"))

    def usual(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">По возможности избегайте боя, если начнет преследовать, убейте!</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Он бежит за нами! Отряд, переходим на УПМ!</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Атаковать титана"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Попытаться улизнуть"))

    def attack(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Вы отлично справились для новеньких! Отряд понес большие потери, поэтому мы возвращаемся за стену, но в следующий раз мы обязательно справимся!</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Вернуться"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Завершить прохождение чат-бота"))

    def escape(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Вы попытались ускакать на лошади вопреки приказу, однако титан сбил Вас на землю.</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">К сожалению, Вашу лошадь раздавил титан...впрочем, и Вас уже тоже.</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">В следующий раз атакуйте! Лучше пасть смертью храбрых!</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Видно не судьба"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Завершить прохождение чат-бота"))

    def deviance(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Заманите его в лес в ловушку!</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Выпускайте гарпуны! Любой ценой захватите живьем!</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Титан схвачен"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Титан улизнул"))

    def garrison(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Добро пожаловать в гарнизон!</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Мы - щит человечества, стоящий на страже стен, и первое ваше задание - патруль на стене Роза.</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Видно титанов?</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Да"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Нет"))

    def yes5(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Готовьтесь к бою, заряжайте пушки!</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Огонь из всех пушек!</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Поздравляю, новички, мы сумели отбиться! Но это был первый раз, посмотрим, что будет дальше. А пока вольно!</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Отдохнуть"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Завершить прохождение чат-бота"))

    def nobody(self):
        self.label.setText(QtCore.QCoreApplication.translate("MainDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans Ms\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">Чиллим пока, ребятки</span></p>"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Comic Sans Ms\'; font-size:10pt; color:#000000;\">А теперь?</span></p></body></html>"))
        self.yesButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Да"))
        self.noButton.setText(QtCore.QCoreApplication.translate("MainDialog", "Нет, хотя... Видно"))
 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainDialog = QtWidgets.QDialog()
    ui = Ui_MainDialog()
    ui.setupUi(MainDialog)
    MainDialog.show()
    sys.exit(app.exec_())
